on:
  pull_request:
    types:
      - closed
    branches:
      - "master"
name: Update version of package
jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set git config email
        run: git config --local user.email "forgwent@gmail.com"
      - name: Set git config name
        run: git config --local user.name "Timofei Kurohtin"
      - name: Get branch name
        run: echo ${{ github.ref_name }}
      - name: Bump version
        run: npm version patch --git-tag-version false
      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: master
      # - name: Publish new version
      #   run: yarn send
