on:
  push:
    branches:
      - "master"
name: Update Version
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set git config email
        run: git config --local user.email "forgwent@gmail.com"
      - name: Set git config name
        run: git config --local user.name "Timofei Kurohtin"
      - name: Bump version
        run: npm version patch --git-tag-version false
      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: master
