on:
  pull_request:
    types:
      - closed
    branches:
      - "master"
name: Update version of package
jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: get_branch_tag
        with:
          msg: ${{ github.head_ref }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set git config email
        run: git config --local user.email "forgwent@gmail.com"
      - name: Set git config name
        run: git config --local user.name "Timofei Kurohtin"
      - name: Output branch tag
        run: echo ${{ steps.get_branch_tag.outputs._0 }}
      - name: Bump version patch
        if: steps.get_branch_tag.outputs._0 == 'hotfix'
        run: npm version patch --git-tag-version false
      - name: Bump version minor
        if: steps.get_branch_tag.outputs._0 == 'feature'
        run: npm version minor --git-tag-version false
      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: master
      # - name: Publish new version
      #   run: yarn send
